//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin1
    {
        [Display(Name = "Admin Id:")]
        public int A_id { get; set; }

        [Display(Name = "Admin Name:")]
        public string A_Name { get; set; }

        [Display(Name = "Password:")]
        public string A_Password { get; set; }
    }
}
