//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class attendance
    {
        [Display(Name = "Admin Id:")]
        public int A_id { get; set; }

        [Display(Name = "Class Id:")]
        public Nullable<int> C_id { get; set; }

        [Display(Name = "Teacher Id:")]
        public Nullable<int> teacher_id { get; set; }

        [Display(Name = "Attendance:")]
        public string Attendance1 { get; set; }

        [Display(Name = "Student Id:")]
        public Nullable<int> R_id { get; set; }

        [Display(Name = "Teacher:")]
        public virtual teacher teacher { get; set; }

        [Display(Name = "Course:")]
        public virtual course course { get; set; }

        [Display(Name = "Registration:")]
        public virtual registeration registeration { get; set; }
    }
}
