//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMSEntities6 : DbContext
    {
        public SMSEntities6()
            : base("name=SMSEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin1> Admin1 { get; set; }
        public virtual DbSet<attendance> attendances { get; set; }
        public virtual DbSet<batch> batches { get; set; }
        public virtual DbSet<course> courses { get; set; }
        public virtual DbSet<registeration> registerations { get; set; }
        public virtual DbSet<student_course> student_course { get; set; }
        public virtual DbSet<teacher> teachers { get; set; }
        public virtual DbSet<teacher_course> teacher_course { get; set; }
        public virtual DbSet<teacher_student> teacher_student { get; set; }
        public virtual DbSet<teacher_tt> teacher_tt { get; set; }
        public virtual DbSet<timetable> timetables { get; set; }
        public virtual DbSet<user1> user1 { get; set; }
    }
}
