//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class teacher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public teacher()
        {
            this.attendances = new HashSet<attendance>();
            this.teacher_course = new HashSet<teacher_course>();
            this.teacher_tt = new HashSet<teacher_tt>();
        }

        [Display(Name = "Teacher Id")]
        public int teacher_id { get; set; }

        [Display(Name = "Teacher Name")]
        public string teacher_name { get; set; }

        [Display(Name = "Teacher Contact")]
        public Nullable<int> teacher_Contact { get; set; }

        [Display(Name = "Teacher Email")]
        public string teacher_Email { get; set; }

        [Display(Name = "Course Id")]
        public Nullable<int> C_id { get; set; }

        [Display(Name = "Password")]
        public string teacher_password { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendance> attendances { get; set; }
        public virtual course course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teacher_course> teacher_course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teacher_tt> teacher_tt { get; set; }
    }
}
