//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teacher_student
    {
        public int t_s_id { get; set; }
        public Nullable<int> t_c_id { get; set; }
        public Nullable<int> C_id { get; set; }
        public Nullable<int> R_id { get; set; }
    
        public virtual course course { get; set; }
        public virtual registeration registeration { get; set; }
        public virtual teacher_course teacher_course { get; set; }
    }
}
